未実装、isuueあり
s-hayashi1104/tpa-03-dog-service pull request #1
Opened 2018-10-04 14:01 UTC by s-hayashi1104

issue
0を渡したときに正しくデータが渡せていない

■未実装
・テストコード
・controller
　400を返す際文字列なども渡る可能性があるので
　判定式を!dog.getDogById(id)に変更する予定

０以外の値をわたしたときは正常に動いていることを確認しています

2018-10-04 14:07 UTC, s-hayashi1104 commented
utisの16,17steps
replace使うべきですね・・

2018-10-04 16:08 UTC, clonable-eden requested changes
@s-hayashi1104 再度考えてみてください！

2018-10-04 16:08 UTC, clonable-eden commented on server/controller.js
> +  if (!dog.getDogById(id)) {
これ、あまりいい書き方じゃないです。見る人が見ればわかるんですが、`!`がどこにかかるかパッと見わからない人もいるので、やるなら
```javascript
if (!(dog.getDogById(id))) {
```
とかにしてちゃんとカッコをつけるかなぁと思いました。
がしかし、今回は別の指摘もあります。まずこの`dog.getDogById(id)`の戻りを保持しなければなりません。理由は、L8でも全く同じ呼び出しをしており、
1. 判定のための呼び出し
2. json responseのための呼び出し
と冗長であるからです。
今回はファイルから読み出した内容をメモリ内で保持しているので負荷にはなりえませんが、これがDBアクセスだったらどうでしょう？Network I/Oが2回発生するので、それが複雑なクエリを持つ重い処理だった場合、ボトルネックになりえます。なので将来のために覚えておいてください。I/Oは重い = なるべく回数を減らすべき、です。

2018-10-04 16:08 UTC, clonable-eden commented on server/controller.js
> +    res.status(400).json({});
jsonを返したら、後続の処理はさせてはならないので、
```javascript
res.status(400).json({});
return;
```
としましょう。

2018-10-04 16:08 UTC, clonable-eden commented on server/utils.js
> +  return { id: params };
このロジックだと、`:`を含むpathが1つのときしか対応できないです。しかもdescriptionにあるような、仮に2つの`:`を含む`pathWithParams`が渡されたときどうなるでしょう？
また、値が文字列になっているので、要件を満たしていないように思えます！

2018-10-05 13:09 UTC, Mitsuru53 commented on server/controller.js
>      res.status(400).json({});
数値は2桁以上でも問題ないはずです
ここのif文は「数値かどうか」という内容に変更しましょう

2018-10-05 13:25 UTC, s-hayashi1104 commented on server/controller.js
>      res.status(400).json({});
@Mitsuru53 
if (typeof id === 'number') {
　if(dogdataにそのidがいるか){
　　return dogdata.json()
　 }
}return 空のjson
という感じですか？？

2018-10-06 06:16 UTC, obber commented on server/utils.js
>      if (v[0] === ':') {
ざっと英語でコメントを書いて、後から訳します。とりあえず英語も残しときますね〜

I tested the app, it looks like this logic is working. Here's my feedback on the code:

1) `v` is not a good variable name for iterating over an array. In this case, perhaps `pathPart` will work.
2) look into how we can be more clear with what's happening by using functions and good function naming. `v[0] === ':'` isn't too clear, so we can name it by putting it in a function:

```
if (beginsWithColon(v)) {
  // ...
}
```

実装はできていますね。アプリを実行して確認しました。コードに関してコメントです：

1) `v` というのは変数名として何を表すのかが分かりにくいから配列の要素を明確にする変数名を選ぼう。例えば、`pathPart` とか。
2) `v[0] === ':'` も同じく、パッと見分かりやすくはないので処理を関数に囲んで、関数名を上手に使ってみよう：

```
if (beginsWithColon(v)) {
  // ...
}
```

2018-10-06 06:16 UTC, obber commented on server/utils.js
> +      const key = v.slice(1);
Again, similar feedback, but I'd name `key` to something more descriptive like `pathParameterName` or `pathParameterKey`, and rename `param` to something like `pathParameterValue`. `key` and `param` doesn't do a good job indicating that it ends up being a key-value pair.

ここも下記のコメントみたいに変数名を帰るのがアドバイスです。`key` と `param` では、最終的にはキーバリューペアになる関係が見えにくいので、
`key` -> `pathParameterKey` か `pathParameterName`
`param` -> `pathParameterValue` とか
はどうでしょうか？

2018-10-06 07:40 UTC, Mitsuru53 commented
ここを見てもらうと
https://github.com/s-hayashi1104/tpa-03-dog-service/blob/master/server/utils.js

こういう入力の時: ‘/posts/3/comments/4’, ‘/posts/:postId/comments/:commentId’
こういう出力: {
    postId: 3,
    commentId: 4
 }がされることが要件ですよね

テストにこちらを追記して実行してみてください
```
expect(parsePathParameters('/posts/3/comments/4', '/posts/:postId/comments/:commentId')).toEqual({postId: 3, commentId: 4});
```
テスト失敗します

またvalueは‘4’などの文字列ではなく4という風に数字を期待しています
テストは
```
expect(parsePathParameters('/api/dog/1', '/api/dog/:id')).toEqual({ 'id': '1' });
```
↓
```
expect(parsePathParameters('/api/dog/1', '/api/dog/:id')).toEqual({ 'id': 1 });
```
ですね
テスト失敗します

2018-10-08 09:56 UTC, clonable-eden requested changes
@s-hayashi1104 コメントしました！

2018-10-08 09:56 UTC, clonable-eden commented on server/utils.test.js
> +describe('parsePathParameters', () => {
同名であれば、1describeの中に2つtestを入れてもOKです。

```javascript
describe('parsePathParameters', () => {
  test('should return an object', () => {
    // ..
  });
  test('should be an object in params', () => {
    // ..
  });
});
```

2018-10-08 09:56 UTC, clonable-eden commented on server/controller.js
> +const dogs = require('./data/dogs.json');
不要。

2018-10-08 09:56 UTC, clonable-eden commented on server/controller.js
> +  return res.status(400).json({});
好みの問題かもしれませんが、ネストを深くする必要はなさそうです。
あと、前に指摘した内容を少し勘違いしているかもしれないので改めて指摘しておくと、データを複数回取得するのはI/Oがネックになりえるから少ない方がいい、というやつですが、これは同じ問い合わせを複数回するのではなく、内容をキャッシュしてそれをもってやればいいんじゃないの？ってことなのです。
```javascript
if (!(typeof id === 'number')) return res.status(400).json({}); // マッチしなかったら返してしまう
const d = dog.getDogById(id); // ここで一回問い合わせて変数に入れる
if (!d) return res.status(400).json({}); // 結果を判定してNGだったら返す
res.json(d); // 正しい結果を返す
```
とすればよいのではないでしょうか（答え書いちゃうけど）。

2018-10-08 10:11 UTC, s-hayashi1104 commented on server/controller.js
> +  return res.status(400).json({});
少し勘違いしてました、。。。
キャッシュしてやればよかったんですね

2018-10-08 10:26 UTC, Mitsuru53 reviewed
こちらを修正よろしくお願いいたします！

2018-10-08 10:26 UTC, Mitsuru53 commented on server/controller.js
> +  if (!(typeof id === 'number')) {
ここの条件はidがnumberじゃない時を判定したいのですよね？

```
if (!(typeof id === 'number'))
```
これはカッコが二重であったりして直感的に読み難い条件文だと思いました

条件は単に以下のように書けるはずです
```
if (typeof id !== 'number')
```

2018-10-08 10:32 UTC, merged